# Generated by Django 5.1.1 on 2024-09-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_poster',
            field=models.ImageField(default='', upload_to='film_posters/'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_trailer',
            field=models.URLField(default=''),
        ),
    ]
