# Generated by Django 5.1.1 on 2024-09-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_film_film_poster_film_film_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_video',
            field=models.FileField(default='', upload_to='film_videos/'),
        ),
    ]
