# Generated by Django 5.1.1 on 2024-09-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_film_film_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_imdb_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
