# Generated by Django 5.1.1 on 2024-09-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_film_film_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
