# Generated by Django 5.1.1 on 2024-09-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_open_image',
            field=models.ImageField(default='', upload_to='film_open_images/'),
        ),
    ]
