# Generated by Django 5.1.1 on 2024-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_film_watch_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesEpisodes',
            fields=[
                ('series_episodes_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_seasons_id', models.IntegerField()),
                ('series_episodes_name', models.CharField(max_length=100)),
                ('series_episodes_number', models.IntegerField()),
                ('series_episodes_description', models.TextField()),
                ('series_episodes_poster', models.ImageField(default='', upload_to='series_episodes_posters/')),
                ('series_episodes_trailer', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesSeasons',
            fields=[
                ('series_seasons_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_id', models.IntegerField()),
                ('series_seasons_name', models.CharField(max_length=100)),
                ('series_seasons_number', models.IntegerField()),
                ('series_seasons_description', models.TextField()),
                ('series_seasons_poster', models.ImageField(default='', upload_to='series_seasons_posters/')),
                ('series_seasons_trailer', models.URLField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='series_video',
        ),
        migrations.AddField(
            model_name='series',
            name='series_season_id',
            field=models.IntegerField(default=0),
        ),
    ]
