# Generated by Django 5.1.1 on 2024-09-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_seriesepisodes_seriesseasons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='series_duration',
        ),
        migrations.AddField(
            model_name='series',
            name='series_episode_count',
            field=models.IntegerField(default=0),
        ),
    ]
