# Generated by Django 5.1.1 on 2024-09-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_seriesseasons_series_id_seriesseasons_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UsersApp',
        ),
    ]
