# Generated by Django 5.1.1 on 2024-09-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_user_usersapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesepisodes',
            name='series_seasons_id',
        ),
        migrations.AddField(
            model_name='seriesepisodes',
            name='series_seasons',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.seriesseasons'),
        ),
    ]
