# Generated by Django 5.1.1 on 2024-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_series_id_seriesepisodes_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesepisodes',
            name='series_episode_video',
            field=models.FileField(default='', upload_to='series_episode_videos/'),
        ),
    ]
