# Generated by Django 5.1.1 on 2024-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_seriesepisodes_series_episode_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='watch_count',
            field=models.IntegerField(default=0),
        ),
    ]
