# Generated by Django 5.1.1 on 2024-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_series_watch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
