# Generated by Django 5.1.1 on 2024-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_film_release_date_film_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesepisodes',
            name='series_episode_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seriesseasons',
            name='series_seasons_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
