# Generated by Django 5.1.1 on 2024-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_seriesepisodes_series_episode_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesseasons',
            name='series_season_episode_count',
            field=models.IntegerField(default=0),
        ),
    ]
