# Generated by Django 5.1.1 on 2024-09-10 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_seriesseasons_series_season_episode_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesepisodes',
            name='episode_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
