# Generated by Django 5.1.1 on 2024-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_seriesepisodes_episode_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='series_open_poster',
            field=models.ImageField(default='', upload_to='series_open_posters/'),
        ),
    ]
