# Generated by Django 5.1.1 on 2024-09-10 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_series_series_open_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinueWatchingFilm',
            fields=[
                ('continue_watching_id', models.AutoField(primary_key=True, serialize=False)),
                ('continue_watching_time', models.DurationField(default=datetime.timedelta(0))),
                ('film', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.film')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
        migrations.CreateModel(
            name='ContinueWatchingSeries',
            fields=[
                ('continue_watching_id', models.AutoField(primary_key=True, serialize=False)),
                ('continue_watching_time', models.DurationField(default=datetime.timedelta(0))),
                ('serie_episode', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.seriesepisodes')),
                ('serie_season', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.seriesseasons')),
                ('series', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.series')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
    ]
