# Generated by Django 5.1.1 on 2024-09-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_userlikelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikelist',
            name='film',
        ),
        migrations.RemoveField(
            model_name='userlikelist',
            name='series',
        ),
        migrations.AddField(
            model_name='userlikelist',
            name='likelist',
            field=models.JSONField(default={'films': [], 'series': []}),
        ),
    ]
