# Generated by Django 5.1.1 on 2024-09-10 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_userlikelist_film_remove_userlikelist_series_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('watchlist', models.JSONField(default={'films': [], 'series': []})),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.usersapp')),
            ],
        ),
    ]
